export const background = '#fff'
export const paleHighlight = '#f5f5f6'
export const lineDark = '#111'
export const lineLight = '#ccc'
export const text = '#111'
export const inactive = '#999'
export const active = 'deeppink'
export const body = '#eee'