export const background = '#eee'
export const lineDark = '#111'
export const lineLight = '#ccc'
export const text = '#111'
export const inactive = '#999'
export const active = 'deeppink'
export const body = '#eee'